data: dataset_path/data.yaml
project: project_dir
name: experiment_name
verbose: True
save: True
epochs: 100
imgsz: 416
batch: -1
patience: 100
fliplr: 0.5
flipud: 0.0
shear: 0.0
perspective: 0.0
mixup: 0.0
degrees: 0.0
translate: 0.1
scale: 0.5
bgr: 0.0
mosaic: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
cutmix: 0.0
auto_augment: randaugment
erasing: 0.4